### ISSUE TITLE
Support for Views

### ISSUE THREAD

**Issue by KollarM** [cup-of-tea-dot-be/entity-framework-core3-mock#1]
I'd like to ask to add support for views to this very interesting library. 
For example I have following configuration:
            modelBuilder.Entity<CompanyInfo>(entity =>
            {
                entity.HasNoKey();
                entity.ToView(Views.CompanyInfoView_Name);
            });

and mocking like this:
            var dbContext = new DbContextMock<BpmDbContext>(new DbContextOptionsBuilder<BpmDbContext>().Options);
            var usersDbSetMock = dbContext.CreateDbSetMock(x => x.CompanyInfo, initialEntities);

and for this I'm getting exception:
EntityFrameworkCore3Mock.Shared.dll ("No key factory could be created for entity type CompanyInfo.....

Any help/hint will be much appreciated

**Comment by huysentruitw** [comment]
Not sure if it will work, but can you try to pass a dummy key-factory to `CreateDbSetMock`?

Like this:

```csharp
var usersDbSetMock = dbContext.CreateDbSetMock(x => x.CompanyInfo, (x, _) => x, initialEntities);
```

**Comment by KollarM** [comment]
Thanks, I have tried that before, also some variants of it. But all of them ended up with NullReferenceException. 
StackTrace:

   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
   at EntityFrameworkCore3Mock.DbSetBackingStore`1.<>c__DisplayClass22_0.<CreateCloneFunc>b__1(PropertyInfo propertyInfo)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.Block(IEnumerable`1 variables, IEnumerable`1 expressions)
   at System.Linq.Expressions.Expression.Block(IEnumerable`1 expressions)
   at EntityFrameworkCore3Mock.DbSetBackingStore`1.CreateCloneFunc(Type entityType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at EntityFrameworkCore3Mock.DbSetBackingStore`1.Clone(TEntity original)
   at EntityFrameworkCore3Mock.DbSetBackingStore`1.<.ctor>b__5_0(TEntity x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at EntityFrameworkCore3Mock.DbSetBackingStore`1..ctor(IEnumerable`1 initialEntities, Func`3 keyFactory)
   at EntityFrameworkCore3Mock.DbSetMock`1..ctor(IEnumerable`1 initialEntities, Func`3 keyFactory, Boolean asyncQuerySupport)
   at EntityFrameworkCore3Mock.DbContextMock`1.CreateDbSetMock[TEntity](Expression`1 dbSetSelector, Func`3 entityKeyFactory, IEnumerable`1 initialEntities)
   at Palfinger.Microservice.BPM.Tests.UnitTests.Service.Services.CompanyManagerServiceTests.GetCompaniesTests.ShouldReturnMyCompanies_WhenNotBpmAgUser(UserDto user) in C:\GIT\Palfinger\Palfinger.Microservice.BPM\Palfinger.Microservice.BPM.Tests\UnitTests\Service\Services\CompanyManagerServiceTests\GetCompaniesTests.cs:line 107

**Comment by huysentruitw** [comment]
```csharp
[Test]
public void DbContextMock_CreateDbSetMock_KeylessModel_ShouldNotThrowException()
{
    var dbContextMock = new DbContextMock<TestDbContext>(Options);
    Assert.DoesNotThrow(() => dbContextMock.CreateDbSetMock(x => x.NoKeyModels, (x, _) => x));
}
```

I created this test above which succeeds, so I have to get an exact reproducible scenario from you... Can you create a minimal DbContext with one Entity. I can only get the same call-stack when one of the initialEntities is `null`, is this what you are trying to do, should one of the models be null?

**Comment by KollarM** [comment]
I downloaded your repo and I have adjusted your Test to make fail. So I have a reproducible case.
But I found that problem is on my side. My entity has private setters (because it is a view)
public class CompanyInfo
    {
        public int CompanyId { get; set; }
        public int PendingUsers { get; private set; }
        public DateTime? LastLogin { get; private set; }
....
    }
Private setters are nice design for this kind of readonly entity, but I can remove them and solve my issue.
Thanks for very fast responses.
If you are still interested how to reproduce the issue, please let me know and I can create a PullRequest or just share a code.

**Comment by huysentruitw** [comment]
Would be good if we could look into supporting private setters as that is a good way to keep your code clean.
