### ISSUE TITLE
Unable to run async calls using CreateDbSetMock

### ISSUE THREAD

**Issue by trisell** [cup-of-tea-dot-be/entity-framework-core3-mock#9]
Currently if I use the CreateDbSetMock with an async call to the database it returns the following:

System.InvalidOperationException : The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.

Is there a way to enable async on a DB context?

**Comment by huysentruitw** [comment]
Normally async should be supported. Which version are you using and can you add a minimal code sample here?

**Comment by trisell** [comment]
So I've essentially implemented the example from the README. Using version 2.1. I have a complex query that is making an async awaited for the db call. When I set it up using the CreateDbContext it give me the following full error. I'm using FirstOrDefaultAsync.

I can't post the code but it's using a complex join query On a couple different Objects.

```
    System.InvalidOperationException : The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.
    Stack Trace:
       at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at <PrivateData>Controller.GetPlan(Int32 planId, Nullable`1 focusedFieldId) in 
<PrivateData>:line 59
   at TestFile in  System.InvalidOperationException : The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.
    Stack Trace:
       at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at <PrivateData>Controller.GetPlan(Int32 planId, Nullable`1 focusedFieldId) in c:\src\AB_INMP\src\INMP.Web\Controllers\PlansController.cs:line 59
   at INMP.Web.Tests.Controllers.PlansControllerTest.TestGetPlanFallowFieldReturnsRedirect() in 
   <PrivateData>:line 88
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)est
   <PrivateData>:line 88
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
```
